-- 추가 상금 및 당첨자 정보 컬럼 추가

ALTER TABLE lotto_draws
ADD COLUMN IF NOT EXISTS first_per_game BIGINT,
ADD COLUMN IF NOT EXISTS second_prize BIGINT,
ADD COLUMN IF NOT EXISTS second_winners INTEGER,
ADD COLUMN IF NOT EXISTS second_per_game BIGINT,
ADD COLUMN IF NOT EXISTS third_prize BIGINT,
ADD COLUMN IF NOT EXISTS third_winners INTEGER,
ADD COLUMN IF NOT EXISTS third_per_game BIGINT,
ADD COLUMN IF NOT EXISTS fourth_prize BIGINT,
ADD COLUMN IF NOT EXISTS fourth_winners INTEGER,
ADD COLUMN IF NOT EXISTS fourth_per_game BIGINT,
ADD COLUMN IF NOT EXISTS fifth_prize BIGINT,
ADD COLUMN IF NOT EXISTS fifth_winners INTEGER,
ADD COLUMN IF NOT EXISTS fifth_per_game BIGINT;
